In [2]:
# Create a NumPy array ‘arr’ of integers from 0 to 5 and print its data type.
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)

int64


In [3]:
#Given a NumPy array 'arr', check if its data type is float64.
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)

int64


In [5]:
#Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
import numpy as np
arr = np.array([1+3j,2+3j,4+5j])
print(arr.dtype)

complex128


In [6]:
# Convert an existing NumPy array 'arr' of integers to float32 data type.
import numpy as np
arr = np.array([1,2,3,4])
arr_float=arr.astype(np.float32)
print(arr_float.dtype)

float32


In [7]:
#Given a NumPy array 'arr' with float64 data type, convert it to float32 to␣
# reduce decimal precision.
import numpy as np
arr = np.array([1.122323456777,2.122345645643,4.122454545423])
arr_float=arr.astype(np.float32)
print(arr_float)
print(arr.dtype)
print(arr_float.dtype)

[1.1223235 2.1223457 4.1224546]
float64
float32


In [9]:
#Write a function array_attributes that takes a NumPy array as input and␣
# returns its shape, size, and data type.
import numpy as np
def array_attributes(arr):
  shape = arr.shape
  size = arr.size
  dtype = arr.dtype
  return shape, size, dtype
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, size, dtype = array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data Type:", dtype)

Shape: (2, 3)
Size: 6
Data Type: int64


In [10]:
#Create a function array_dimension that takes a NumPy array as input and␣
# returns its dimensionality.
6
import numpy as np
def array_dimension(arr):
  dimension = arr.ndim
  return dimension
arr = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
dimension = array_dimension(arr)
print("dimension", dimension)

dimension 2


In [11]:
#Design a function item_size_info that takes a NumPy array as input and returns␣
#the item size and the total size in bytes.
import numpy as np
def item_size_info(arr):

  item_size = arr.itemsize # Size of each element in bytes
  total_size = arr.nbytes # Total size of the array in bytes
  return item_size, total_size
# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
item_size, total_size = item_size_info(arr)
print("Item size (bytes):", item_size)
print("Total size (bytes):", total_size)

Item size (bytes): 4
Total size (bytes): 24


In [13]:
#Design a function shape_stride_relationship that takes a NumPy array as input␣
# and returns the shape and strides of the array.
import numpy as np
def shape_stride_relationship(arr):
  return arr.shape, arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)

Shape: (2, 3)
Strides: (24, 8)


In [14]:
#Create a function create_zeros_array that takes an integer n as input and␣
# returns a NumPy array of zeros with n elements.
def create_zeros_array(n):
  return np.zeros(n)
# Example usage
zeros_array = create_zeros_array(5)
print(zeros_array)

[0. 0. 0. 0. 0.]


In [15]:
#Write a function create_ones_matrix that takes integers rows and cols as␣
# inputs and generates a 2D NumPy array filled with ones of size rows x cols.
def create_ones_matrix(rows, cols):
  return np.ones((rows, cols))
# Example usage
ones_matrix = create_ones_matrix(3, 4)
print(ones_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
#Write a function generate_range_array that takes three integers start, stop,␣
# and step as arguments and creates a NumPy array with a range starting from␣
#start, ending at stop (exclusive), and with the specified step.
def generate_range_array(start, stop, step):
  return np.arange(start, stop, step)
# Example usage
range_array = generate_range_array(0, 10, 2)
print(range_array)

[0 2 4 6 8]


In [18]:
#Design a function generate_linear_space that takes two floats start, stop, and␣
# an integer num as arguments and generates a NumPy array with num equally␣
# spaced values between start and stop (inclusive).
def generate_linear_space(start, stop, num):
  return np.linspace(start, stop, num)
# Example usage
linear_space = generate_linear_space(0, 10, 5)
print(linear_space)

[ 0.   2.5  5.   7.5 10. ]


In [19]:
#Create a function create_identity_matrix that takes an integer n as input and␣
# generates a square identity matrix of size n x n using numpy.eye.
def create_identity_matrix(n):
  return np.eye(n)
# Example usage
identity_matrix = create_identity_matrix(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [20]:
#Write a function that takes a Python list and converts it into a NumPy array.
def list_to_numpy_array(py_list):
  return np.array(py_list)
# Example usage
py_list = [1, 2, 3, 4]
numpy_array = list_to_numpy_array(py_list)
print(numpy_array)

[1 2 3 4]


In [21]:
#Create a NumPy array and demonstrate the use of numpy.view to create a new␣
# array object with the same data.
def array_view(arr):
  return arr.view()

# Example usage
arr = np.array([1.5, 2.6, 3.7])
view_arr = array_view(arr)
print(view_arr)

[1.5 2.6 3.7]


In [22]:
#Create a function array_strides that takes a NumPy array as input and returns␣
# the strides of the array. arr = np.array([1.5, 2.6, 3.7])
def array_strides(arr):
  return arr.strides
# Example usage
arr = np.array([1.5, 2.6, 3.7])
strides = array_strides(arr)
print("Strides:", strides)

Strides: (8,)


In [23]:
#Write a function that takes two NumPy arrays and concatenates them along a␣
# specified axis.
def concatenate_arrays(arr1, arr2, axis=0):
  return np.concatenate((arr1, arr2), axis=axis)
# Example usage
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
concatenated_array = concatenate_arrays(arr1, arr2)
print(concatenated_array)

[1 2 3 4 5 6]


In [24]:
#Create two NumPy arrays with different shapes and concatenate them␣
# horizontally using `numpy.
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
concatenated_array = np.hstack((arr1, arr2))
print(concatenated_array)

[[1 2 5 6]
 [3 4 7 8]]


In [25]:
#Write a function that vertically stacks multiple NumPy arrays given as a list.
import numpy as np

def vertical_stack(arr_list):
  return np.vstack(arr_list)
# Example usage
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])
stacked_array = vertical_stack([arr1, arr2, arr3])
print(stacked_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
#Write a Python function using NumPy to create an array of integers within a␣
# specified range (inclusive) with a given step size.
def create_integer_array(start, stop, step):
  return np.arange(start, stop + 1, step)
# Example usage
integer_array = create_integer_array(1, 10, 2)
print(integer_array)

[1 3 5 7 9]


In [27]:
#Write a Python function using NumPy to generate an array of 10 equally spaced␣
# values between 0 and 1 (inclusive).
def generate_equally_spaced():
  return np.linspace(0, 1, 10)
# Example usage
equally_spaced_array = generate_equally_spaced()
print(equally_spaced_array)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [29]:
#Write a Python function using NumPy to create an array of 5 logarithmically␣
# spaced values between 1 and 1000 (inclusive).
def generate_log_spaced():
  return np.logspace(0, 3, 5)
# Example usage
log_spaced_array = generate_log_spaced()
print(log_spaced_array)

[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [30]:
#Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3␣
# columns, where the values are random integers between 1 and 100.
import pandas as pd

# Create a NumPy array with random integers between 1 and 100
random_array = np.random.randint(1, 101, size=(5, 3))

# Convert the NumPy array to a Pandas DataFrame
df = pd.DataFrame(random_array, columns=['A', 'B', 'C'])
print(df)

    A   B   C
0  58  29  24
1  29  45  66
2  19  13  85
3  31  76  49
4  97  93  76


In [31]:
#Write a function that takes a Pandas DataFrame and replaces all negative␣
# values in a specific column with zeros. Use NumPy operations within the␣
# andas DataFrame.
def replace_negative_values(df, column_name):
  df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
  return df
# Example usage
df = pd.DataFrame({'A': [1, -2, 3, -4], 'B': [-5, 6, -7, 8]})
print("Original DataFrame:")
print(df)
df = replace_negative_values(df, 'A')
print("\nDataFrame after replacing negative values in column 'A':")
print(df)

Original DataFrame:
   A  B
0  1 -5
1 -2  6
2  3 -7
3 -4  8

DataFrame after replacing negative values in column 'A':
   A  B
0  1 -5
1  0  6
2  3 -7
3  0  8


In [32]:
#Access the 3rd element from the given NumPy array.
def access_third_element(arr):
  return arr[2]
# Example usage
arr = np.array([10, 20, 30, 40, 50])
third_element = access_third_element(arr)
print("3rd Element:", third_element)

3rd Element: 30


In [33]:
#Retrieve the element at index (1, 2) from the 2D NumPy array.
def retrieve_element(arr):
  return arr[1, 2]
# Example usage
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
element = retrieve_element(arr_2d)
print("Element at index (1, 2):", element)

Element at index (1, 2): 6


In [34]:
#Using boolean indexing, extract elements greater than 5 from the given NumPy␣
# array.
def extract_greater_than_five(arr):
  return arr[arr > 5]
# Example usage
arr = np.array([1, 3, 5, 7, 9])
extracted_elements = extract_greater_than_five(arr)
print("Elements greater than 5:", extracted_elements)

Elements greater than 5: [7 9]


In [35]:
#Perform basic slicing to extract elements from index 2 to 5 (inclusive) from␣
#the given NumPy array.
def basic_slicing(arr):
  return arr[2:6]
# Example usage
arr = np.array([10, 20, 30, 40, 50, 60, 70])
sliced_elements = basic_slicing(arr)
print("Sliced Elements:", sliced_elements)

Sliced Elements: [30 40 50 60]


In [36]:
# #"""Slice the 2D NumPy array to extract the sub-array [[2, 3], [5, 6]] from␣
# ↪the given array. arr = np.array([10, 20, 30, 40, 50]) arr = np.array([3, 8,␣
# ↪2, 10, 5, 7]) arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]) arr_2d = np.
# ↪array([[1, 2, 3],
# [4, 5, 6],
# [7, 8, 9]])
# arr_2d = np.array([[1, 2, 3],
# [4, 5, 6],
# [7, 8, 9]])"""
import numpy as np
arr_2d = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])
# Extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]
print(sub_array)

[[2 3]
 [5 6]]


In [37]:
#Write a NumPy function to extract elements in specific order from a given 2D␣
# array based on indices provided in another array.
def extract_elements_by_indices(arr, indices):
  return arr[indices[:, 0], indices[:, 1]]
14
# Example usage
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([[0, 1], [1, 2], [2, 0]]) # Indices of elements to extract
extracted_elements = extract_elements_by_indices(arr_2d, indices)
print(extracted_elements)

[2 6 7]


In [38]:
# Create a NumPy function that filters elements greater than a threshold from a␣
# given 1D array using boolean indexing.
def filter_elements_greater_than_threshold(arr, threshold):
  return arr[arr > threshold]
# Example usage
arr = np.array([3, 8, 2, 10, 5, 7])
filtered_elements = filter_elements_greater_than_threshold(arr, 5)
print(filtered_elements)

[ 8 10  7]


In [42]:
# Develop a NumPy function that extracts specific elements from a 3D array␣
# using indices provided in three separate arrays for each dimension.
def extract_elements_from_3d_array(arr, indices_x, indices_y, indices_z):
  return arr[indices_x, indices_y, indices_z]
# Example usage
arr_3d = np.random.randint(1, 10, size=(4, 4, 4))
indices_x = np.array([0, 1, 2])
indices_y = np.array([0, 2, 3])
indices_z = np.array([1, 3, 0])
extracted_elements = extract_elements_from_3d_array(arr_3d, indices_x,indices_y, indices_z)
print(extracted_elements)

[2 6 6]


In [44]:
# Write a NumPy function that returns elements from an array where both two␣
# conditions are satisfied using boolean indexing.
def extract_elements_with_conditions(arr, condition1, condition2):
  return arr[(condition1) & (condition2)]
# Example usage
arr = np.array([10, 20, 30, 40, 50])
condition1 = arr > 20 # Elements greater than 20
condition2 = arr < 50 # Elements less than 50
extracted_elements = extract_elements_with_conditions(arr, condition1,condition2)
print(extracted_elements)

[30 40]


In [46]:
# Create a NumPy function that extracts elements from a 2D array using row and␣
# column indices provided in separate arrays.
def extract_elements_by_row_col(arr, row_indices, col_indices):
  return arr[row_indices, col_indices]
# Example usage
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 2])
col_indices = np.array([1, 2])
extracted_elements = extract_elements_by_row_col(arr_2d, row_indices,col_indices)
print(extracted_elements)

[2 9]


In [47]:
 # Given an array arr of shape (3, 3), add a scalar value of 5 to each element␣
# using NumPy broadcasting.
def add_scalar_using_broadcasting(arr, scalar):
  return arr + scalar
# Example usage
arr_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = add_scalar_using_broadcasting(arr_3x3, 5)
print(result)



[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [48]:
# Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply␣
# each row of arr2 by the corresponding element in arr1 using NumPy␣
# broadcasting.
def multiply_rows_by_corresponding_elements(arr1, arr2):
  return arr2 * arr1.T # Transpose arr1 to match the shape of arr2
# Example usage
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]])
result = multiply_rows_by_corresponding_elements(arr1, arr2)
print(result)


[[ 4  5  6]
 [14 16 18]
 [30 33 36]]


In [49]:
# Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3),␣
# add arr1 to each row of arr2 using NumPy broadcasting.
def add_row_to_each(arr1, arr2):
  return arr2 + arr1
# Example usage
arr1 = np.array([1, 2, 3]) # Shape (1, 3)
arr2 = np.array([[4, 5, 6], [7, 8, 9], [10, 11, 12]]) # Shape (3, 3)
result = add_row_to_each(arr1, arr2)
print(result)


[[ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [50]:
# Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these␣
# arrays using NumPy broadcasting.
def add_arrays_using_broadcasting(arr1, arr2):
  return arr1 + arr2
# Example usage
arr1 = np.array([[1], [2], [3]]) # Shape (3, 1)
arr2 = np.array([[4, 5, 6]]) # Shape (1, 3)
result = add_arrays_using_broadcasting(arr1, arr2)
print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [51]:
 # Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform␣
# multiplication using NumPy broadcasting. Handle the shape incompatibility.
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]]) # Shape (2, 3)
arr2 = np.array([[1, 2], [3, 4]]) # Shape (2, 2)
# Matrix multiplication (dot product)
result = np.dot(arr1, arr2)
print(result)


ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [52]:
 # Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean = np.mean(arr, axis=0)
print(column_mean)


[2.5 3.5 4.5]


In [53]:
# Find maximum value in each row of the given array:
row_max = np.max(arr, axis=1)
print(row_max)

[3 6]


In [54]:
# For the given array, find indices of maximum value in each column.
indices_max_column = np.argmax(arr, axis=0)
print(indices_max_column)

[1 1 1]


In [56]:
# For the given array, apply custom function to calculate moving sum along rows.
def moving_sum(arr):
  return np.cumsum(arr, axis=1)
arr = np.array([[1, 2, 3], [4, 5, 6]])
moving_sum_result = moving_sum(arr)
print(moving_sum_result)


[[ 1  3  6]
 [ 4  9 15]]


In [57]:
# In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])
# Check if all elements in each column are even
even_check = np.all(arr % 2 == 0, axis=0)
print(even_check)


[False False False]


In [58]:
# arr = np.array([[1, 2, 3], [4, 5, 6]]) arr = np.array([[1, 2, 3], [4, 5, 6]])␣
# ↪arr = np.array([[1, 2, 3], [4, 5, 6]]) arr = np.array([[1, 2, 3], [4, 5,␣
# ↪6]]) arr = np.array([[2, 4, 6], [3, 5, 7]]) 46. Given a NumPy array arr,␣
# ↪reshape it into a matrix of dimensions m rows and n columns. Return the␣
# ↪reshaped matrix.
arr = np.array([1, 2, 3, 4, 5, 6])
# Reshape into 2 rows and 3 columns
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)


[[1 2 3]
 [4 5 6]]


In [59]:
# Create a function that takes a matrix as input and returns the flattened␣
# array.
def flatten_matrix(matrix):
  return matrix.flatten()
arr = np.array([[1, 2, 3], [4, 5, 6]])
flattened_arr = flatten_matrix(arr)
print(flattened_arr)

[1 2 3 4 5 6]


In [60]:
# Write a function that concatenates two given arrays along a specified axis.
def concatenate_arrays(arr1, arr2, axis):
  return np.concatenate((arr1, arr2), axis=axis)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
# Concatenate along axis 0 (vertically)
concatenated_arr = concatenate_arrays(arr1, arr2, axis=0)
print(concatenated_arr)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [62]:
# Create a function that splits an array into multiple sub-arrays along a␣
# specified axis.
def split_array(arr, indices, axis):
  return np.split(arr, indices, axis=axis)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Split along axis 0 (rows)
split_arr = split_array(arr, [1, 2], axis=0)
for sub_array in split_arr:
  print(sub_array)


[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


In [63]:
# Write a function that inserts and then deletes elements from a given array at specified indices.
def insert_and_delete(arr, insert_idx, insert_values, delete_idx):
  arr = np.insert(arr, insert_idx, insert_values)
  arr = np.delete(arr, delete_idx)
  return arr
arr = np.array([1, 2, 3, 4, 5])
# Insert [6, 7] at index 2, then delete element at index 3
modified_arr = insert_and_delete(arr, 2, [6, 7], 3)
print(modified_arr)


[1 2 6 3 4 5]


In [64]:
# Create a NumPy array arr1 with random integers and another array arr2 with␣
# integers from 1 to 10. Perform element-wise addition between arr1 and arr2.
import numpy as np
arr1 = np.random.randint(1, 10, size=5) # Random integers
arr2 = np.arange(1, 11, 2) # Integers from 1 to 10
result_addition = arr1 + arr2
print("Element-wise addition:", result_addition)

Element-wise addition: [ 7 12  7 14 11]


In [65]:
 # Generate a NumPy array arr1 with sequential integers from 10 to 1 and another␣
# array arr2 with integers from 1 to 10. Subtract arr2 from arr1 element-wise.
arr1 = np.arange(10, 0, -1) # Sequential integers from 10 to 1
arr2 = np.arange(1, 11) # Integers from 1 to 10
result_subtraction = arr1 - arr2
print("Element-wise subtraction:", result_subtraction)


Element-wise subtraction: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [66]:
# Create a NumPy array arr1 with random integers and another array arr2 with␣
# ↪integers from 1 to 5. Perform element-wise multiplication between arr1 and␣
# ↪arr2.
arr1 = np.random.randint(1, 10, size=5) # Random integers
arr2 = np.arange(1, 6) # Integers from 1 to 5
result_multiplication = arr1 * arr2
print("Element-wise multiplication:", result_multiplication)


Element-wise multiplication: [ 1 10 21 24 40]


In [67]:
# Generate a NumPy array arr1 with even integers from 2 to 10 and another array␣
# ↪arr2 with integers from 1 to 5. Perform element-wise division of arr1 by␣
# ↪arr2.
arr1 = np.arange(2, 12, 2) # Even integers from 2 to 10
arr2 = np.arange(1, 6) # Integers from 1 to 5
result_division = arr1 / arr2
print("Element-wise division:", result_division)

Element-wise division: [2. 2. 2. 2. 2.]


In [68]:
# Create a NumPy array arr1 with integers from 1 to 5 and another array arr2␣
# ↪with the same numbers reversed. Calculate the exponentiation of arr1 raised␣
# ↪to the power of arr2 element-wise.
arr1 = np.array([1, 2, 3, 4, 5]) # Integers from 1 to 5
arr2 = arr1[::-1] # Reverse of arr1
result_exponentiation = arr1 ** arr2
print("Element-wise exponentiation:", result_exponentiation)

Element-wise exponentiation: [ 1 16 27 16  5]


In [69]:
# Write a function that counts the occurrences of a specific substring within a␣
# NumPy array of strings.
def count_substring(arr, substring):
  return np.char.count(arr, substring)
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
occurrences = count_substring(arr, substring)
print(f"Occurrences of '{substring}':", occurrences)


Occurrences of 'hello': [1 0 1 0 1]


In [70]:
# Write a function that extracts uppercase characters from a NumPy array of␣
# strings.
def extract_uppercase(arr):
  return np.char.add(np.char.upper(arr), '')
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
uppercase_chars = extract_uppercase(arr)
print("Uppercase characters:", uppercase_chars)


Uppercase characters: ['HELLO' 'WORLD' 'OPENAI' 'GPT']


In [73]:
# original_array = np.array([1, 2, 3, 4, 5, 6]) input_matrix = np.array([[1, 2,␣
# ↪3], [4, 5, 6]]) original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])␣
# ↪arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello']) arr = np.
# ↪array(['Hello', 'World', 'OpenAI', 'GPT']) array1 = np.array([[1, 2], [3,␣
# ↪4]]) array2 = np.array([[5, 6], [7, 8]]) original_array = np.array([1, 2, 3,␣
# ↪4, 5]) indices_to_insert = [2, 4] values_to_insert = [10, 11]␣
# ↪indices_to_delete = [1, 3] 58. Write a function that replaces occurrences of␣
# ↪a substring in a NumPy array of strings with a new string.
def replace_substring(arr, old, new):
  return np.char.replace(arr, old, new)
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
replaced_array = replace_substring(arr, 'hello', 'hi')
print("Replaced array:", replaced_array)

Replaced array: ['hi' 'world' 'hi' 'numpy' 'hi']


In [76]:
# Write a function that concatenates strings in a NumPy array element-wise.
def concatenate_strings(arr):
  return np.char.add(arr[:-1], arr[1:])
arr = np.array(['hello', 'world', 'numpy'])
concatenated = concatenate_strings(arr)
print("Concatenated strings:", concatenated)

Concatenated strings: ['helloworld' 'worldnumpy']


In [78]:
# Write a function that finds the length of the longest string in a NumPy array.
def longest_string_length(arr):
  return np.max(np.char.str_len(arr))
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
longest_length = longest_string_length(arr)
print("Length of the longest string:", longest_length)

Length of the longest string: 9


In [79]:
 # Create a dataset of 100 random integers between 1 and 1000. Compute the mean,␣
# ↪median, variance, and standard deviation of the dataset using NumPy's␣
# ↪functions.
import numpy as np
# Generate 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, size=100)
# Calculate mean, median, variance, and standard deviation
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_deviation}")


Mean: 450.0
Median: 430.5
Variance: 71444.32
Standard Deviation: 267.2907031679179


In [80]:
# Generate an array of 50 random numbers between 1 and 100. Find the 25th and␣
# 75th percentiles of the dataset.
# Generate 50 random numbers between 1 and 100
random_numbers = np.random.randint(1, 101, size=50)
# Calculate 25th and 75th percentiles
percentile_25 = np.percentile(random_numbers, 25)
percentile_75 = np.percentile(random_numbers, 75)
print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")


25th Percentile: 29.5
75th Percentile: 79.0


In [81]:
# Create two arrays representing two sets of variables. Compute the correlation␣
# coefficient between these arrays using NumPy's corrcoef function.
# Create two arrays representing two sets of variables
arr1 = np.random.rand(50) # Random array of 50 elements
arr2 = np.random.rand(50) # Another random array of 50 elements
# Compute the correlation coefficient
correlation_matrix = np.corrcoef(arr1, arr2)
correlation_coefficient = correlation_matrix[0, 1]
print(f"Correlation Coefficient: {correlation_coefficient}")


Correlation Coefficient: 0.15817279002256737


In [82]:
 # Create two matrices and perform matrix multiplication using NumPy's dot␣
# function.
# Create two matrices
matrix1 = np.random.randint(1, 10, (3, 2)) # 3x2 matrix
matrix2 = np.random.randint(1, 10, (2, 4)) # 2x4 matrix
# Perform matrix multiplication
result_matrix = np.dot(matrix1, matrix2)
print("Matrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Result of Matrix Multiplication:\n", result_matrix)


Matrix 1:
 [[6 8]
 [6 6]
 [6 6]]
Matrix 2:
 [[2 8 6 8]
 [5 6 4 7]]
Result of Matrix Multiplication:
 [[ 52  96  68 104]
 [ 42  84  60  90]
 [ 42  84  60  90]]


In [83]:
 # Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th␣
# (median), and 90th percentiles along with the first and third quartiles.
# Generate 50 integers between 10 and 1000
int_array = np.random.randint(10, 1001, size=50)
# Calculate percentiles and quartiles
percentile_10 = np.percentile(int_array, 10)
percentile_50 = np.percentile(int_array, 50) # Median
percentile_90 = np.percentile(int_array, 90)
q1 = np.percentile(int_array, 25) # First quartile
q3 = np.percentile(int_array, 75) # Third quartile
print(f"10th Percentile: {percentile_10}")
print(f"50th Percentile (Median): {percentile_50}")
print(f"90th Percentile: {percentile_90}")
print(f"First Quartile (Q1): {q1}")
print(f"Third Quartile (Q3): {q3}")


10th Percentile: 101.20000000000002
50th Percentile (Median): 586.0
90th Percentile: 917.2
First Quartile (Q1): 401.25
Third Quartile (Q3): 813.0


In [84]:
# Create a NumPy array of integers and find the index of a specific element.
# Generate a random array of integers
arr = np.random.randint(1, 20, size=10)
# Find the index of a specific element (e.g., 10)
element = 10
index = np.where(arr == element)
print(f"Array: {arr}")
print(f"Index of element {element}: {index}")


Array: [ 4 13 10 14  1 10  4 14 14 12]
Index of element 10: (array([2, 5]),)


In [85]:
# Generate a random NumPy array and sort it in ascending order.
# Generate a random array
arr = np.random.randint(1, 100, size=10)
# Sort the array in ascending order
sorted_arr = np.sort(arr)
print(f"Original Array: {arr}")
print(f"Sorted Array: {sorted_arr}")


Original Array: [61 33 15 95 79 16 46  4 78 17]
Sorted Array: [ 4 15 16 17 33 46 61 78 79 95]


In [86]:
# Filter elements >20 in the given NumPy array.
# Generate a random array of integers
arr = np.random.randint(1, 50, size=15)
# Filter elements greater than 20
filtered_arr = arr[arr > 20]
print(f"Original Array: {arr}")
print(f"Filtered Array (elements > 20): {filtered_arr}")


Original Array: [39 25 43 29 14 36 24 37 17 23 24 35 38 44 28]
Filtered Array (elements > 20): [39 25 43 29 36 24 37 23 24 35 38 44 28]


In [87]:
# Filter elements which are divisible by 3 from a given NumPy array.
# Generate a random array of integers
arr = np.random.randint(1, 50, size=15)
# Filter elements divisible by 3
filtered_by_3 = arr[arr % 3 == 0]
print(f"Original Array: {arr}")
print(f"Filtered Array (divisible by 3): {filtered_by_3}")


Original Array: [ 3 19 36  9 10 19 38 10 28 10 24 22 35 49 35]
Filtered Array (divisible by 3): [ 3 36  9 24]


In [89]:
# Filter elements which are  20 and  40 from a given NumPy array
# Generate a random array of integers
arr = np.random.randint(1, 50, size=15)
# Filter elements between 20 and 40 (inclusive)
filtered_range = arr[(arr >= 20) & (arr <= 40)]
print(f"Original Array: {arr}")
print(f"Filtered Array (20 and 40): {filtered_range}")

Original Array: [47 33 20 24  6 23 21 20 30 33 15 14 49 39 40]
Filtered Array (20 and 40): [33 20 24 23 21 20 30 33 39 40]


In [91]:
# For the given NumPy array, check its byte order using the dtype attribute␣
# byteorder.
import numpy as np
arr = np.array([12, 25, 6, 42, 8, 30])
# Check byte order using dtype's byteorder attribute
byte_order = arr.dtype.byteorder
print(f"Byte order of the array: {byte_order}")

Byte order of the array: =


In [93]:
# arr = np.array(['apple', 'banana', 'grape', 'pineapple']) arr = np.
# ↪array(['apple', 'banana', 'grape', 'pineapple']) arr = np.array([12, 25, 6,␣
# ↪42, 8, 30]) arr = np.array([1, 5, 8, 12, 15]) arr = np.array([10, 20, 30,␣
# ↪40, 50]) arr = np.array([1, 2, 3]) arr1 = np.array(['Hello', 'World']) arr2␣
# ↪= np.array(['Open', 'AI']) 72. For the given NumPy array, perform byte␣
# ↪swapping in place using byteswap().
arr = np.array([12, 25, 6, 42, 8, 30], dtype='>i4') # Big-endian integer array
# Perform byte swapping in place
arr.byteswap(inplace=True)
print(f"Array after byte swapping: {arr}")

Array after byte swapping: [201326592 419430400 100663296 704643072 134217728 503316480]


In [97]:
# For the given NumPy array, swap its byte order without modifying the original␣
# array using newbyteorder().
arr = np.array([12, 25, 6, 42, 8, 30], dtype='>i4') # Big-endian integer array
# Swap byte order without modifying the original array
swapped_arr = arr.newbyteorder()
print(f"Original array: {arr}")
print(f"Array with swapped byte order: {swapped_arr}")


AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

In [98]:
# For the given NumPy array and swap its byte order conditionally based on␣system endianness using newbyteorder().
arr = np.array([12, 25, 6, 42, 8, 30], dtype='>i4') # Big-endian integer array
# Swap byte order based on system endianness
swapped_conditionally = arr.newbyteorder('S') # 'S' makes it conditional on␣system endianness
print(f"Conditionally swapped byte order: {swapped_conditionally}")


AttributeError: `newbyteorder` was removed from the ndarray class in NumPy 2.0. Use `arr.view(arr.dtype.newbyteorder(order))` instead.

In [100]:
# For the given NumPy array, check if byte swapping is necessary for the␣current system using dtype attribute byteorder.
arr = np.array([12, 25, 6, 42, 8, 30], dtype='>i4') # Big-endian integer array
# Check if byte swapping is necessary based on the system's byte order
if arr.dtype.byteorder != '=':
  print("Byte swapping is necessary.")
else:
  print("Byte order is compatible with the system.")


Byte swapping is necessary.


In [101]:
# Create a NumPy array arr1 with values from 1 to 10. Create a copy of arr1␣
# ↪named copy_arr and modify an element in copy_arr. Check if modifying␣
# ↪copy_arr affects arr1.
arr1 = np.array([1, 2, 3, 4, 5])
# Create a copy of arr1
copy_arr = arr1.copy()
# Modify an element in copy_arr
copy_arr[0] = 10
28
print("Original array (arr1):", arr1)
print("Modified copy (copy_arr):", copy_arr)

Original array (arr1): [1 2 3 4 5]
Modified copy (copy_arr): [10  2  3  4  5]


In [102]:
 # Create a 2D NumPy array matrix of shape (3, 3) with random integers. Extract␣
# ↪a slice view_slice from the matrix. Modify an element in view_slice and␣
# ↪observe if it changes the original matrix.
matrix = np.random.randint(1, 10, size=(3, 3))
# Extract a slice view
view_slice = matrix[1:, 1:]
# Modify an element in view_slice
view_slice[0, 0] = 100
print("Original matrix:")
print(matrix)
print("Modified slice view:")
print(view_slice)


Original matrix:
[[  2   4   8]
 [  3 100   1]
 [  8   4   5]]
Modified slice view:
[[100   1]
 [  4   5]]


In [103]:
# Create a NumPy array array_a of shape (4, 3) with sequential integers from 1␣
# ↪to 12. Extract a slice view_b from array_a and broadcast the addition of 5␣
# ↪to view_b. Check if it alters the original array_a.
array_a = np.arange(1, 13).reshape(4, 3)
# Extract a slice view
view_b = array_a[:2, :2]
# Add 5 to the slice view
view_b += 5
print("Original array (array_a):")
print(array_a)
print("Modified slice view (view_b):")
print(view_b)


Original array (array_a):
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]
Modified slice view (view_b):
[[ 6  7]
 [ 9 10]]


In [104]:
# Create a NumPy array orig_array of shape (2, 4) with values from 1 to 8.␣
# ↪Create a reshaped view reshaped_view of shape (4, 2) from orig_array. Modify␣
# ↪an element in reshaped_view and check if it reflects changes in the original␣
# ↪orig_array.
orig_array = np.arange(1, 9).reshape(2, 4)
# Create a reshaped view
reshaped_view = orig_array.reshape(4, 2)
# Modify an element in the reshaped view
reshaped_view[0, 0] = 100
print("Original array (orig_array):")
print(orig_array)
print("Modified reshaped view (reshaped_view):")
print(reshaped_view)


Original array (orig_array):
[[100   2   3   4]
 [  5   6   7   8]]
Modified reshaped view (reshaped_view):
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [105]:
# Create a NumPy array data of shape (3, 4) with random integers. Extract a␣
# ↪copy data_copy of elements greater than 5. Modify an element in data_copy␣
# ↪and verify if it affects the original data.
data = np.random.randint(1, 20, size=(3, 4))
# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()
# Modify an element in the copy
data_copy[0] = 100
print("Original data:")
30
print(data)
print("Modified data copy:")
print(data_copy)

Original data:
[[ 2  3  2  3]
 [ 6 15 13 11]
 [12 17 15  4]]
Modified data copy:
[100  15  13  11  12  17  15]


In [106]:
# Create two matrices A and B of identical shape containing integers and␣
# ↪perform addition and subtraction operations between them.
import numpy as np
# Create two matrices A and B of identical shape
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[6, 5, 4], [3, 2, 1]])
# Perform addition
addition_result = A + B
# Perform subtraction
subtraction_result = A - B
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Addition (A + B):\n", addition_result)
print("Subtraction (A - B):\n", subtraction_result)

Matrix A:
 [[1 2 3]
 [4 5 6]]
Matrix B:
 [[6 5 4]
 [3 2 1]]
Addition (A + B):
 [[7 7 7]
 [7 7 7]]
Subtraction (A - B):
 [[-5 -3 -1]
 [ 1  3  5]]


In [107]:
 # Generate two matrices C (3x2) and D (2x4) and perform matrix multiplication.
# Create matrices C and D
C = np.random.randint(1, 10, size=(3, 2)) # 3x2 matrix
D = np.random.randint(1, 10, size=(2, 4)) # 2x4 matrix
# Perform matrix multiplication
multiplication_result = np.dot(C, D)
print("Matrix C (3x2):\n", C)
print("Matrix D (2x4):\n", D)
print("Matrix multiplication (C x D):\n", multiplication_result)


Matrix C (3x2):
 [[2 4]
 [3 1]
 [9 1]]
Matrix D (2x4):
 [[6 6 3 7]
 [9 7 4 5]]
Matrix multiplication (C x D):
 [[48 40 22 34]
 [27 25 13 26]
 [63 61 31 68]]


In [108]:
# Create a matrix E and find its transpose.
# Create a matrix E
E = np.random.randint(1, 10, size=(4, 3)) # 4x3 matrix
# Find the transpose of matrix E
transpose_E = E.T
print("Matrix E (4x3):\n", E)
print("Transpose of matrix E (3x4):\n", transpose_E)


Matrix E (4x3):
 [[6 6 6]
 [9 5 3]
 [7 5 3]
 [8 2 9]]
Transpose of matrix E (3x4):
 [[6 9 7 8]
 [6 5 5 2]
 [6 3 3 9]]


In [109]:
# Generate a square matrix F and compute its determinant.
# Create a square matrix F (e.g., 3x3 matrix)
F = np.random.randint(1, 10, size=(3, 3)) # 3x3 matrix
# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)
print("Matrix F (3x3):\n", F)
print("Determinant of matrix F:", determinant_F)

Matrix F (3x3):
 [[1 1 6]
 [9 5 4]
 [7 2 2]]
Determinant of matrix F: -90.0


In [110]:
# Create a square matrix G and find its inverse
# Create a square matrix G (e.g., 2x2 matrix)
G = np.array([[4, 7], [2, 6]])
# Compute the inverse of matrix G
inverse_G = np.linalg.inv(G)
print("Matrix G (2x2):\n", G)
print("Inverse of matrix G:\n", inverse_G)


Matrix G (2x2):
 [[4 7]
 [2 6]]
Inverse of matrix G:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
